services:
  cameras-web:
    image: nginx:1.27-alpine
    container_name: hikvision-cameras-web
    restart: unless-stopped
    volumes:
      - ./site:/usr/share/nginx/html:ro
    networks:
      npm_proxy:
        aliases:
          - cameras-web

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: hikvision-mediamtx
    restart: unless-stopped
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    networks:
      npm_proxy:
        aliases:
          - mediamtx

networks:
  npm_proxy:
    external: true
    name: npm_proxy
